# Generated by Django 3.1.3 on 2020-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tag',
            field=models.CharField(choices=[('Important', 'Important'), ('Urgent', 'Urgent')], max_length=15, null=True),
        ),
    ]
